version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Required Approvals Check'
    validate:
      - do: approvals
        min:
          count: 0
        limit:
          teams: ['tech_leads']
