###
# Global trigger action for automations related to PR events
###

name: PR automation

on:
  pull_request_target:
    types: [ opened, closed, review_requested, review_request_removed, assigned, unassigned ]
  pull_request_review:
    types: [ submitted ]
      
# calls reusable workflow located in special .github-internal repo
jobs:
  handle_pr_automation:
    uses: Auburn-CWS/.github-internal/.github/workflows/handle_pr_automation.yml@main
    secrets: inherit
