name: Replicate global workflows across organization

on:
  push:
    branches: [ dev ]
  workflow_dispatch: {}
  
jobs:

  replicate_changes:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: derberg/manage-files-in-multiple-repositories@v2.1.0
        with:
          github_token: ${{ secrets.GLOBAL_WORKFLOW_REPLICATION_PAT }}
          patterns_to_include: '.github/workflows'
          # must have, so the workflow do not copy this workflow file to all other repos. It should be only in one, main, .github repo
          patterns_to_ignore: '.github/workflows/replicate_global_workflows.yml'
